<a href="https://colab.research.google.com/github/Neel12-coder/Python-Datascience/blob/main/Python_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
list1=["Python","Java","C","C++"]
print(min(list1))

C


In [ ]:
str1 = "6/4"
print("str1")

str1


In [ ]:
d1={"abc":1,"def":5,"ghi":6}
d1["abc"]

1

In [ ]:
i=2
while i>0:
  print(i)
  i=i-1

2
1


In [ ]:
str ="Stack of books"
print(len(str))

14


In [ ]:
str1 ="Information"
str1[2:8]

'format'

In [ ]:
if False:
  print("inside if block")
elif True:
  print("inside elif block")
else:
  print("inside else block")

inside elif block


#NumPy

Numerical Python
##Types of NumPy Array
-> 1 Dimensional Array
-> 2 Dimensional Matrices

In [ ]:
a=[1,2,4,5]

In [ ]:
import numpy as np

In [ ]:
np.array(a)

array([1, 2, 4, 5])

In [ ]:
b= [[1,2,3],[4,5,6]]

In [ ]:
np.array(b)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#generating numpy arrays
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#adding third argument i.e stepsize
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((3,1))

array([[1.],
       [1.],
       [1.]])

In [ ]:
np.arange(1,10,2) #third arg is stepsize

array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(1,10,7) #third arg is divide it into 7 portions

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [ ]:
# generating identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(3) #generates uniformly distributed values between 0 and 1

array([0.7679489 , 0.08453497, 0.12526403])

In [ ]:
np.random.rand(2,3)

array([[0.67736064, 0.76146115, 0.35367076],
       [0.98078685, 0.82372996, 0.43590754]])

In [ ]:
np.random.randn(7) # generates guassian distributed values

array([-1.50389517, -0.12918815, -1.04448735, -0.83742341,  0.37011465,
        0.03450567, -2.03345287])

In [ ]:
#if you need just randon integers, 1st arg = lower limit and 2nd arg= upper limit
np.random.randint(1,100)

40

In [ ]:
# to get array provide 3rd arg
np.random.randint(1,10,4)

array([2, 6, 1, 8])

In [ ]:
a= 56.4
print("a=",id(a))
b=float("56.4")
print("b=",id(b))

a= 140702513978192
b= 140702515129008


In [ ]:
c = 50.2
d= 6.2
e=c+d
print("e=",id(e))

e= 140702452679184


In [ ]:
f=float(c)+float(d)
print("f=",id(f))

f= 140702452679760


In [ ]:
j ="56.4"
print("j=",id(j))

j= 140702452015728


In [ ]:
#mathematical functions

import math as m

a= -54.558
print(m.ceil(a))
print(m.fabs(a))
print(m.floor(a))
print(m.factorial(5))


-54
54.558
-55
120


In [ ]:
import numpy as np
a= np.arange(25)

In [ ]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [ ]:
b= np.random.randint(1,100,10)

In [ ]:
print(b)

[69 43 47 70 13  8 26 64 86 63]


In [ ]:
a.reshape(5,5) # take care that there should be 5*5=25 elements in original array a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
np.max(b)

86

In [ ]:
np.min(b)

8

In [ ]:
np.argmax(b) #to get the position of max and min

8

In [ ]:
np.argmin(b)

5

In [ ]:
# to know dimension of array 
c= a.reshape(5,5)
print(c)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
c.shape #to know shape

(5, 5)

In [ ]:
c.dtype # to know datatype

dtype('int64')

#**Numpy Indexing**

In [ ]:
a= np.arange(10)

In [ ]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[4]

4

In [ ]:
a[-1:-5]

array([], dtype=int64)

In [ ]:
a[-1]

9

In [ ]:
a[2:6]

array([2, 3, 4, 5])

#**INDEX BROADCASTING**

In [ ]:
#broadcasting in numpy
a[2:5]=100
a

array([  0,   1, 100, 100, 100,   5,   6,   7,   8,   9])

In [ ]:
b = a[3:6]
print(b)
b[:] = 100
print(b)

[100 100   5]
[100 100 100]


In [ ]:
print(a) #changes in b (slice of a) affects array a .... numpy saves memory, hence...

[  0   1 100 100 100 100   6   7   8   9]


In [ ]:
# to avoid any changes in a.. declare it as copy
b= a.copy()

In [ ]:
b[:] = 11

In [ ]:
b

array([11, 11, 11, 11, 11, 11, 11, 11, 11, 11])

In [ ]:
print(a) # a not affected

[  0   1 100 100 100 100   6   7   8   9]


In [ ]:
c = np.array([[1,2,3],[3,4,5],[2,3,4]])

In [ ]:
c

array([[1, 2, 3],
       [3, 4, 5],
       [2, 3, 4]])

In [ ]:
c[1][2]

5

In [ ]:
c[2,2]

4

#**Extracting Submatrices**

In [ ]:
print(c)

[[1 2 3]
 [3 4 5]
 [2 3 4]]


In [ ]:
c[1:,:2]

array([[3, 4],
       [2, 3]])

#**Conditional Indexing**

In [ ]:
a = np.arange(10)

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = a>5

In [ ]:
b

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [ ]:
a[b]

array([6, 7, 8, 9])

In [ ]:
a[a>3] #this is called conditional indexing

array([4, 5, 6, 7, 8, 9])

#**Numpy Operations**

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a + a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
a-a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
a / a

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
a + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a - 1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [ ]:
a / 0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [ ]:
1 / a

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

#**Numpy Operations**
## To know more

### visit : https://numpy.org/doc/stable/reference/ufuncs.html

In [ ]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.log(a)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])